imports_granularity = "Crate"

use_field_init_shorthand = true
use_try_shorthand = true

normalize_comments = true
wrap_comments = true

reorder_impl_items = true

match_block_trailing_comma = true

blank_lines_upper_bound = 2
